# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/artifacts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgp.proto import dataset_pb2 as dgp_dot_proto_dot_dataset__pb2
from dgp.proto import remote_pb2 as dgp_dot_proto_dot_remote__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64gp/proto/artifacts.proto\x12\tdgp.proto\x1a\x17\x64gp/proto/dataset.proto\x1a\x16\x64gp/proto/remote.proto\"\x83\x01\n\x10\x44\x61tasetArtifacts\x12,\n\x08metadata\x18\x01 \x01(\x0b\x32\x1a.dgp.proto.DatasetMetadata\x12+\n\x08\x61rtifact\x18\x02 \x01(\x0b\x32\x19.dgp.proto.RemoteArtifact\x12\x14\n\x0c\x64\x65rived_from\x18\x03 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.artifacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATASETARTIFACTS']._serialized_start=90
  _globals['_DATASETARTIFACTS']._serialized_end=221
# @@protoc_insertion_point(module_scope)
