"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019-2021 Toyota Research Institute.  All rights reserved.
Definitions for annotation types for images and point clouds
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _FeatureType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FeatureTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FeatureType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AGENT_2D: _FeatureType.ValueType  # 0
    """Feature type of default 2D agents."""
    AGENT_3D: _FeatureType.ValueType  # 1
    """Feature type of default 3D agents."""
    EGO_INTENTION: _FeatureType.ValueType  # 2
    """Feature type of ego intent ontology."""
    CORRIDOR: _FeatureType.ValueType  # 3
    """Feature type of corridor map element."""
    INTERSECTION: _FeatureType.ValueType  # 4
    """Feature type of intersection."""
    PARKED_CAR: _FeatureType.ValueType  # 5
    """Feature type of parked car ontology."""

class FeatureType(_FeatureType, metaclass=_FeatureTypeEnumTypeWrapper):
    """Generic Feature Type Enumeration.
    Features will be available under the corresponding enum name.
    """

AGENT_2D: FeatureType.ValueType  # 0
"""Feature type of default 2D agents."""
AGENT_3D: FeatureType.ValueType  # 1
"""Feature type of default 3D agents."""
EGO_INTENTION: FeatureType.ValueType  # 2
"""Feature type of ego intent ontology."""
CORRIDOR: FeatureType.ValueType  # 3
"""Feature type of corridor map element."""
INTERSECTION: FeatureType.ValueType  # 4
"""Feature type of intersection."""
PARKED_CAR: FeatureType.ValueType  # 5
"""Feature type of parked car ontology."""
global___FeatureType = FeatureType

class _FeatureValueType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FeatureValueTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FeatureValueType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NUMERIC: _FeatureValueType.ValueType  # 0
    """Feature value type of numeric values."""
    FILE: _FeatureValueType.ValueType  # 1
    """Feature value type of file."""

class FeatureValueType(_FeatureValueType, metaclass=_FeatureValueTypeEnumTypeWrapper):
    """The feature value type specified in dgp.ontology.FeatureOntologyItem."""

NUMERIC: FeatureValueType.ValueType  # 0
"""Feature value type of numeric values."""
FILE: FeatureValueType.ValueType  # 1
"""Feature value type of file."""
global___FeatureValueType = FeatureValueType
