# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/features.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgp.proto import geometry_pb2 as dgp_dot_proto_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64gp/proto/features.proto\x12\tdgp.proto\x1a\x18\x64gp/proto/geometry.proto*l\n\x0b\x46\x65\x61tureType\x12\x0c\n\x08\x41GENT_2D\x10\x00\x12\x0c\n\x08\x41GENT_3D\x10\x01\x12\x11\n\rEGO_INTENTION\x10\x02\x12\x0c\n\x08\x43ORRIDOR\x10\x03\x12\x10\n\x0cINTERSECTION\x10\x04\x12\x0e\n\nPARKED_CAR\x10\x05*)\n\x10\x46\x65\x61tureValueType\x12\x0b\n\x07NUMERIC\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATURETYPE']._serialized_start=65
  _globals['_FEATURETYPE']._serialized_end=173
  _globals['_FEATUREVALUETYPE']._serialized_start=175
  _globals['_FEATUREVALUETYPE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
