# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/file_datum.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64gp/proto/file_datum.proto\x12\tdgp.proto\x1a\x19google/protobuf/any.proto\"\xc8\x01\n\tFileDatum\x12,\n\x05\x64\x61tum\x18\x01 \x01(\x0b\x32\x1d.dgp.proto.SelfDescribingFile\x12:\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32%.dgp.proto.FileDatum.AnnotationsEntry\x1aQ\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.dgp.proto.SelfDescribingFile:\x02\x38\x01\"L\n\x12SelfDescribingFile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12$\n\x06schema\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.file_datum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEDATUM_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_FILEDATUM_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_FILEDATUM']._serialized_start=69
  _globals['_FILEDATUM']._serialized_end=269
  _globals['_FILEDATUM_ANNOTATIONSENTRY']._serialized_start=188
  _globals['_FILEDATUM_ANNOTATIONSENTRY']._serialized_end=269
  _globals['_SELFDESCRIBINGFILE']._serialized_start=271
  _globals['_SELFDESCRIBINGFILE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
