"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019 Toyota Research Institute.  All rights reserved."""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DatumId(google.protobuf.message.Message):
    """Unique identifier to a sample/datum in a specific dataset log

    For certain scenarios, the sample_name will also include the directory/session
    name to make the sample name unique to the dataset.
    For internal datasets, this would be the relevant log information
    for traceability purposes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOG_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    log: builtins.str
    """Log identifier

    For TRI / internal datasets:
      log = <robot_name>/<session_name>/<log_id>.<ext>

    Public datasets:
    For e.g. The KITTI raw dataset contains camera 02 images under
       2011_09_26/2011_09_26_drive_0001_sync/image_02/data/0000000042.png
    The corresponding unique log_id would be:
      log = 2011_09_26/2011_09_26_drive_0001_sync
    """
    name: builtins.str
    """Datum name (i.e. camera_0, lidar_0)
    Alternatively, this serves as a datum identifier for public datasets,
    or untraceable datasets

    For public datasets where the datasets are derived from non-sequential logs,
    the name might be a sufficient identifier for a datum.
    For e.g., filename=rgb/1aa6dd36-aa7f0108.jpg, name=1aa6dd36-aa7f0108

    For datums without unique names, only if the datums can not be traced,
    generate a sha1 hash of the datum contents.
    """
    index: builtins.int
    """Index within the log (if available)

    For TRI / internal datasets:
    Frame index required to find the image within the associated .mkv file.

    For public datasets:
    For e.g. The KITTI raw dataset contains camera 02 images under
    2011_09_26/2011_09_26_drive_0001_sync/image_02/data/0000000042.png
    The corresponding unique index would be: 42
    """
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp within the log (if available)"""

    def __init__(
        self,
        *,
        log: builtins.str = ...,
        name: builtins.str = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["index", b"index", "log", b"log", "name", b"name", "timestamp", b"timestamp"]) -> None: ...

global___DatumId = DatumId
