# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/ontology.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64gp/proto/ontology.proto\x12\x0c\x64gp.proto.v2\"\xab\x01\n\x0cOntologyItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12/\n\x05\x63olor\x18\x03 \x01(\x0b\x32 .dgp.proto.v2.OntologyItem.Color\x12\x0f\n\x07isthing\x18\x04 \x01(\x08\x12\x15\n\rsupercategory\x18\x05 \x01(\t\x1a(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\"5\n\x08Ontology\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.dgp.proto.v2.OntologyItem\"K\n\x13\x46\x65\x61tureOntologyItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\x1a\n\x12\x66\x65\x61ture_value_type\x18\x03 \x01(\r\"C\n\x0f\x46\x65\x61tureOntology\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.dgp.proto.v2.FeatureOntologyItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.ontology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONTOLOGYITEM']._serialized_start=43
  _globals['_ONTOLOGYITEM']._serialized_end=214
  _globals['_ONTOLOGYITEM_COLOR']._serialized_start=174
  _globals['_ONTOLOGYITEM_COLOR']._serialized_end=214
  _globals['_ONTOLOGY']._serialized_start=216
  _globals['_ONTOLOGY']._serialized_end=269
  _globals['_FEATUREONTOLOGYITEM']._serialized_start=271
  _globals['_FEATUREONTOLOGYITEM']._serialized_end=346
  _globals['_FEATUREONTOLOGY']._serialized_start=348
  _globals['_FEATUREONTOLOGY']._serialized_end=415
# @@protoc_insertion_point(module_scope)
