# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/remote.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64gp/proto/remote.proto\x12\tdgp.proto\"\x1b\n\nRemotePath\x12\r\n\x05value\x18\x01 \x01(\t\"Q\n\x0eRemoteArtifact\x12\"\n\x03url\x18\x01 \x01(\x0b\x32\x15.dgp.proto.RemotePath\x12\x0c\n\x04sha1\x18\x02 \x01(\t\x12\r\n\x05isdir\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.remote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REMOTEPATH']._serialized_start=37
  _globals['_REMOTEPATH']._serialized_end=64
  _globals['_REMOTEARTIFACT']._serialized_start=66
  _globals['_REMOTEARTIFACT']._serialized_end=147
# @@protoc_insertion_point(module_scope)
