"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019 Toyota Research Institute.  All rights reserved."""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RemotePath(google.protobuf.message.Message):
    """A remote path that specifies the url of a file or directory
    For e.g. HTTP or S3 url (http://, s3://)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___RemotePath = RemotePath

@typing.final
class RemoteArtifact(google.protobuf.message.Message):
    """Artifact that is hosted in a remote location as defined by RemotePath"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    SHA1_FIELD_NUMBER: builtins.int
    ISDIR_FIELD_NUMBER: builtins.int
    sha1: builtins.str
    """sha1sum of the artifact contents.
    In the case where the artifact
    is a full directory, the sha1 is generated by computing the
    sha1sum on the compressed directory.
    i.e. via `tar -cf - <dir> | sha1sum`.
    """
    isdir: builtins.bool
    """Whether the remote artifact is a directory or a file.
    In the case of directory, the sha1 is generated by
    computing the sha1sum on the compressed directory.
    i.e. via `tar -cf - <dir> | sha1sum`.
    """
    @property
    def url(self) -> global___RemotePath:
        """Remote path of the artifact."""

    def __init__(
        self,
        *,
        url: global___RemotePath | None = ...,
        sha1: builtins.str = ...,
        isdir: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["url", b"url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["isdir", b"isdir", "sha1", b"sha1", "url", b"url"]) -> None: ...

global___RemoteArtifact = RemoteArtifact
