# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/sample.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from dgp.proto import file_datum_pb2 as dgp_dot_proto_dot_file__datum__pb2
from dgp.proto import geometry_pb2 as dgp_dot_proto_dot_geometry__pb2
from dgp.proto import identifiers_pb2 as dgp_dot_proto_dot_identifiers__pb2
from dgp.proto import image_pb2 as dgp_dot_proto_dot_image__pb2
from dgp.proto import point_cloud_pb2 as dgp_dot_proto_dot_point__cloud__pb2
from dgp.proto import radar_point_cloud_pb2 as dgp_dot_proto_dot_radar__point__cloud__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64gp/proto/sample.proto\x12\tdgp.proto\x1a\x19google/protobuf/any.proto\x1a\x1a\x64gp/proto/file_datum.proto\x1a\x18\x64gp/proto/geometry.proto\x1a\x1b\x64gp/proto/identifiers.proto\x1a\x15\x64gp/proto/image.proto\x1a\x1b\x64gp/proto/point_cloud.proto\x1a!dgp/proto/radar_point_cloud.proto\"x\n\x11SampleCalibration\x12\r\n\x05names\x18\x01 \x03(\t\x12/\n\nintrinsics\x18\x02 \x03(\x0b\x32\x1b.dgp.proto.CameraIntrinsics\x12#\n\nextrinsics\x18\x03 \x03(\x0b\x32\x0f.dgp.proto.Pose\"\xd1\x01\n\nDatumValue\x12!\n\x05image\x18\x01 \x01(\x0b\x32\x10.dgp.proto.ImageH\x00\x12,\n\x0bpoint_cloud\x18\x02 \x01(\x0b\x32\x15.dgp.proto.PointCloudH\x00\x12*\n\nfile_datum\x18\x03 \x01(\x0b\x32\x14.dgp.proto.FileDatumH\x00\x12\x37\n\x11radar_point_cloud\x18\x04 \x01(\x0b\x32\x1a.dgp.proto.RadarPointCloudH\x00\x42\r\n\x0b\x64\x61tum_oneof\"~\n\x05\x44\x61tum\x12\x1e\n\x02id\x18\x01 \x01(\x0b\x32\x12.dgp.proto.DatumId\x12\x0b\n\x03key\x18\x02 \x01(\t\x12$\n\x05\x64\x61tum\x18\x03 \x01(\x0b\x32\x15.dgp.proto.DatumValue\x12\x10\n\x08next_key\x18\x04 \x01(\t\x12\x10\n\x08prev_key\x18\x05 \x01(\t\"\xcf\x01\n\x06Sample\x12\x1e\n\x02id\x18\x01 \x01(\x0b\x32\x12.dgp.proto.DatumId\x12\x12\n\ndatum_keys\x18\x02 \x03(\t\x12\x17\n\x0f\x63\x61libration_key\x18\x03 \x01(\t\x12\x31\n\x08metadata\x18\x04 \x03(\x0b\x32\x1f.dgp.proto.Sample.MetadataEntry\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLE_METADATAENTRY']._loaded_options = None
  _globals['_SAMPLE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLECALIBRATION']._serialized_start=234
  _globals['_SAMPLECALIBRATION']._serialized_end=354
  _globals['_DATUMVALUE']._serialized_start=357
  _globals['_DATUMVALUE']._serialized_end=566
  _globals['_DATUM']._serialized_start=568
  _globals['_DATUM']._serialized_end=694
  _globals['_SAMPLE']._serialized_start=697
  _globals['_SAMPLE']._serialized_end=904
  _globals['_SAMPLE_METADATAENTRY']._serialized_start=835
  _globals['_SAMPLE_METADATAENTRY']._serialized_end=904
# @@protoc_insertion_point(module_scope)
