# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/scene.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgp.proto import sample_pb2 as dgp_dot_proto_dot_sample__pb2
from dgp.proto import statistics_pb2 as dgp_dot_proto_dot_statistics__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64gp/proto/scene.proto\x12\tdgp.proto\x1a\x16\x64gp/proto/sample.proto\x1a\x1a\x64gp/proto/statistics.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x03\n\x05Scene\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03log\x18\x03 \x01(\t\x12\"\n\x07samples\x18\x04 \x03(\x0b\x32\x11.dgp.proto.Sample\x12\x30\n\x08metadata\x18\x05 \x03(\x0b\x32\x1e.dgp.proto.Scene.MetadataEntry\x12\x1e\n\x04\x64\x61ta\x18\x06 \x03(\x0b\x32\x10.dgp.proto.Datum\x12\x31\n\rcreation_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\nontologies\x18\x08 \x03(\x0b\x32 .dgp.proto.Scene.OntologiesEntry\x12\x30\n\nstatistics\x18\t \x01(\x0b\x32\x1c.dgp.proto.DatasetStatistics\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x1a\x31\n\x0fOntologiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\x06Scenes\x12 \n\x06scenes\x18\x01 \x03(\x0b\x32\x10.dgp.proto.Scene\"\x1f\n\nSceneFiles\x12\x11\n\tfilenames\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.scene_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_METADATAENTRY']._loaded_options = None
  _globals['_SCENE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SCENE_ONTOLOGIESENTRY']._loaded_options = None
  _globals['_SCENE_ONTOLOGIESENTRY']._serialized_options = b'8\001'
  _globals['_SCENE']._serialized_start=149
  _globals['_SCENE']._serialized_end=599
  _globals['_SCENE_METADATAENTRY']._serialized_start=479
  _globals['_SCENE_METADATAENTRY']._serialized_end=548
  _globals['_SCENE_ONTOLOGIESENTRY']._serialized_start=550
  _globals['_SCENE_ONTOLOGIESENTRY']._serialized_end=599
  _globals['_SCENES']._serialized_start=601
  _globals['_SCENES']._serialized_end=643
  _globals['_SCENEFILES']._serialized_start=645
  _globals['_SCENEFILES']._serialized_end=676
# @@protoc_insertion_point(module_scope)
