"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019-2021 Toyota Research Institute.  All rights reserved.
Definitions for a scene within a dataset.
"""

import builtins
import collections.abc
import dgp.proto.sample_pb2
import dgp.proto.statistics_pb2
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Scene(google.protobuf.message.Message):
    """A single scene consisting of sequential frames in a robot session."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.any_pb2.Any: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.any_pb2.Any | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class OntologiesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LOG_FIELD_NUMBER: builtins.int
    SAMPLES_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CREATION_DATE_FIELD_NUMBER: builtins.int
    ONTOLOGIES_FIELD_NUMBER: builtins.int
    STATISTICS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Unique name for a scene

    For public datasets where the scenes are uniquely identified,
    the scene name is directly used.

    For scenes without without unique names, generate a sha1 hash of
    all the datum keys combined.
    """
    description: builtins.str
    """Optional, short description of the scene (~200 characters)"""
    log: builtins.str
    """Log identifier
    Refer to dgp.identifiers.proto for more information.
    """
    @property
    def samples(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dgp.proto.sample_pb2.Sample]:
        """List of samples corresponding to this scene."""

    @property
    def metadata(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.any_pb2.Any]:
        """Optional metadata (i.e. miscellaneous enriched scene-level annotations)."""

    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dgp.proto.sample_pb2.Datum]:
        """List of Datum's contained in this Scene."""

    @property
    def creation_date(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Date and timestamp of scene creation."""

    @property
    def ontologies(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.str]:
        """Task-specific ontologies
        Ontologies are stored under <scene_dir>/ontology/<ontology_sha1>.json
        Maps dgp.proto.AnnotationType (segmentation, instances, etc) to the filename
        containing the ontology for the specific AnnotationType/Task.
        """

    @property
    def statistics(self) -> dgp.proto.statistics_pb2.DatasetStatistics:
        """Scene statistics
        SceneDataset statistics will be aggregated on-the-fly.
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        description: builtins.str = ...,
        log: builtins.str = ...,
        samples: collections.abc.Iterable[dgp.proto.sample_pb2.Sample] | None = ...,
        metadata: collections.abc.Mapping[builtins.str, google.protobuf.any_pb2.Any] | None = ...,
        data: collections.abc.Iterable[dgp.proto.sample_pb2.Datum] | None = ...,
        creation_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ontologies: collections.abc.Mapping[builtins.int, builtins.str] | None = ...,
        statistics: dgp.proto.statistics_pb2.DatasetStatistics | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["creation_date", b"creation_date", "statistics", b"statistics"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["creation_date", b"creation_date", "data", b"data", "description", b"description", "log", b"log", "metadata", b"metadata", "name", b"name", "ontologies", b"ontologies", "samples", b"samples", "statistics", b"statistics"]) -> None: ...

global___Scene = Scene

@typing.final
class Scenes(google.protobuf.message.Message):
    """List of scenes"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCENES_FIELD_NUMBER: builtins.int
    @property
    def scenes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Scene]: ...
    def __init__(
        self,
        *,
        scenes: collections.abc.Iterable[global___Scene] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["scenes", b"scenes"]) -> None: ...

global___Scenes = Scenes

@typing.final
class SceneFiles(google.protobuf.message.Message):
    """A collection of scenes"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAMES_FIELD_NUMBER: builtins.int
    @property
    def filenames(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Relative file paths for the json files serialized from Scene message.

        A Scene message is serialized and stored under the following naming convention:
           <scene_dir>/scene_<scene_hash>.json
        where <scene_hash> is the deterministic deterministic SHA1 hash hexdigest of a scene and served
        as the version of the scene, see dgp.utils.protobuf.generate_uid_from_pbobject
        for details.
        """

    def __init__(
        self,
        *,
        filenames: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filenames", b"filenames"]) -> None: ...

global___SceneFiles = SceneFiles
